name: CI Begineer
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: configure python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: execute test
        run: |
          pytest tests/ -v
      
      - name: Ejecutar con cobertura
        run: |
          pytest --cov=app --cov-report=term --cov-report=html

      - name: Guardar reporte
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
