name: docker self-hosted runner
on:
  push:
    branches: [feature/**]
  workflow_dispatch: 

jobs:
  docker-build:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: "003"

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: build docker
      run: docker build -t myapp:runner .
    
    - name: test docker
      run: |
        CONTAINER_NAME=app-runner
        docker run -d --name $CONTAINER_NAME -p 5000:5000 myapp:runner
        sleep 10
        curl -f http://localhost:5000/health
        docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME